apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: item-management-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dmolio/micro.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://XXXXXXXX.gr7.us-east-1.eks.amazonaws.com # Replace with your cluster's API server endpoint
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
