apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-management-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: item-management-api
  template:
    metadata:
      labels:
        app: item-management-api
    spec:
      containers:
      - name: item-management-api
        image: dmolio/item-management-api:0b2a54aaf5e6d08ec8e0a417afb5864eae10c507
        ports:
        - containerPort: 5001
